model: vllm_two_pass
model_args:
  pretrained: google/gemma-3-12b-it
  max_thinking_tokens: 8192
  dtype: bfloat16
  gpu_memory_utilization: 0.9
  max_model_len: 16384
  peft_model: null
include_path: ./config/tasks
tasks:
  - spatial_eval_gen_rag
  - spatial_eval_gen
limit: 1500
apply_chat_template: true
num_fewshot: 0
batch_size: 8
device: cuda:0
log_samples: true
output_path: ./results/deepseek-r1-distill-qwen-1.5b-two-pass/
